m = float(int(input("Digite quantos metros: ")))
c = int(m * 100)
dc = int(m * 10)
mm = int(m * 1000)
dec = float(m / 10)
hm = float(m / 100)
km = float(m / 1000)
print("Com a medida de {} metros você tem {} centímetros, {:.0f} milímetros".format(m, c, dc, mm))
print("assim como {} decâmetros, {} hectômetros e {} quilômetros".format(dec, hm, km))
